version: '4.23.0'

services:
  product-server:
    image: 'postgres'
    container_name: my-postgres-container-new
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres